[package]
name = "libjpeg"
authors = ["MozJPEG & libjpeg-turbo Authors", "Stephen Crane <sjc@immunant.com>"]
version = "0.0.0"
publish = false
edition = "2018"

[lib]
name = "jpeg"
path = "lib.rs"
crate_type = ["dylib"]

[dependencies]
libc = "0.2"
mozjpeg = {path = "../"}
